# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eyAInKni6qTiOWd8D3OWLGOVW6ht_87u
"""

x=5
print(f"變數x的值是:{x}")
print(f"變數x的記憶體地址是:{id(x)}")